project_id = "zlwpxflqtyhdwanmupgy"

[functions.create-delivery-checkout]
verify_jwt = false

[functions.verify-delivery-payment]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.request-refund]
verify_jwt = false

<<<<<<< HEAD
[functions.verify-subscription-payment]
verify_jwt = false

[functions.process-subscription]
verify_jwt = false

[functions.complete-delivery-order]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
=======
[functions.process-subscription]
verify_jwt = false
>>>>>>> 194462f (autosync: update 2026-01-15T11:01:14.329Z)
